//! Windows answer-file generation (Rufus's "user experience" options).
//!
//! The XML is dropped at `sources/$OEM$/$$/Panther/unattend.xml` on the
//! target media; Windows setup copies `$OEM$\$$` onto the installed drive
//! and picks the answer file up from `%WINDIR%\Panther` automatically.

use crate::protocol::WinOptions;

/// Generate a minimal `unattend.xml` implementing `opts`.
pub fn generate(opts: &WinOptions) -> String {
    let mut runsync: Vec<String> = Vec::new();
    let mut first_logon: Vec<String> = Vec::new();

    if opts.hw_bypass {
        // Classic LabConfig switches, applied while WinPE is running.
        for key in [
            "BypassTPMCheck",
            "BypassSecureBootCheck",
            "BypassRAMCheck",
            "BypassCPUCheck",
            "BypassStorageCheck",
        ] {
            runsync.push(labconfig_cmd(key));
        }
    }
    if opts.no_bitlocker {
        // Runs in the full OS after install: keep device encryption off.
        first_logon.push(xml_escape(
            r#"reg add HKLM\SYSTEM\CurrentControlSet\Control\BitLocker /v PreventDeviceEncryption /t REG_DWORD /d 1 /f"#,
        ));
    }
    if opts.no_online_account {
        // Prefer local accounts: hide the forced online-account screens and
        // skip most privacy questions (harmless no-op where unsupported).
        first_logon.push(xml_escape(
            r#"reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE /v HideOnlineAccountScreens /t REG_DWORD /d 1 /f"#,
        ));
        first_logon.push(xml_escape(
            r#"reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE /v BypassNRO /t REG_DWORD /d 1 /f"#,
        ));
    }

    let mut xml = String::from(
        r#"<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Ferrus -->
<unattend xmlns="urn:schemas-microsoft-com:unattend">
"#,
    );

    if !runsync.is_empty() {
        xml.push_str("  <settings pass=\"windowsPE\">\n");
        xml.push_str(
            "    <component name=\"Microsoft-Windows-Setup\" processorArchitecture=\"amd64\" publicKeyToken=\"31bf3856ad364e35\" language=\"neutral\" versionScope=\"nonSxS\">\n",
        );
        xml.push_str("      <RunSynchronous>\n");
        for (i, cmd) in runsync.iter().enumerate() {
            xml.push_str(&format!(
                "        <RunSynchronousCommand wcm:action=\"add\" xmlns:wcm=\"http://schemas.microsoft.com/WMIConfig/2002/State\">\n\
                 \x20         <Order>{}</Order>\n\
                 \x20         <Path>{}</Path>\n\
                 \x20       </RunSynchronousCommand>\n",
                i + 1,
                cmd
            ));
        }
        xml.push_str("      </RunSynchronous>\n");
        xml.push_str("    </component>\n");
        xml.push_str("  </settings>\n");
    }

    if !first_logon.is_empty() || opts.no_online_account {
        xml.push_str("  <settings pass=\"oobeSystem\">\n");
        xml.push_str(
            "    <component name=\"Microsoft-Windows-Shell-Setup\" processorArchitecture=\"amd64\" publicKeyToken=\"31bf3856ad364e35\" language=\"neutral\" versionScope=\"nonSxS\">\n",
        );
        if opts.no_online_account {
            xml.push_str("      <OOBE>\n");
            xml.push_str("        <HideOnlineAccountScreens>true</HideOnlineAccountScreens>\n");
            xml.push_str("        <HideWirelessSetupInOOBE>false</HideWirelessSetupInOOBE>\n");
            xml.push_str("        <ProtectYourPC>3</ProtectYourPC>\n");
            xml.push_str("      </OOBE>\n");
        }
        if !first_logon.is_empty() {
            xml.push_str("      <FirstLogonCommands>\n");
            for cmd in &first_logon {
                xml.push_str(&format!(
                    "        <SynchronousCommand wcm:action=\"add\" xmlns:wcm=\"http://schemas.microsoft.com/WMIConfig/2002/State\">\n\
                     \x20         <CommandLine>{}</CommandLine>\n\
                     \x20         <Description>Ferrus configuration</Description>\n\
                     \x20       </SynchronousCommand>\n",
                    cmd
                ));
            }
            xml.push_str("      </FirstLogonCommands>\n");
        }
        xml.push_str("    </component>\n");
        xml.push_str("  </settings>\n");
    }

    xml.push_str("</unattend>\n");
    xml
}

fn labconfig_cmd(key: &str) -> String {
    format!(
        r#"reg add HKLM\SYSTEM\Setup\LabConfig /v {key} /t REG_DWORD /d 1 /f"#
    )
}

fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_options_produce_minimal_file() {
        let xml = generate(&WinOptions::default());
        assert!(xml.starts_with("<?xml"));
        assert!(xml.contains("</unattend>"));
        assert!(!xml.contains("LabConfig"));
        assert!(!xml.contains("FirstLogonCommands"));
    }

    #[test]
    fn hw_bypass_lists_all_labconfig_keys() {
        let xml = generate(&WinOptions {
            hw_bypass: true,
            ..Default::default()
        });
        assert!(xml.contains("<settings pass=\"windowsPE\">"));
        for key in [
            "BypassTPMCheck",
            "BypassSecureBootCheck",
            "BypassRAMCheck",
            "BypassCPUCheck",
            "BypassStorageCheck",
        ] {
            assert!(xml.contains(key), "missing {key}");
        }
    }

    #[test]
    fn account_and_bitlocker_land_in_oobe_pass() {
        let xml = generate(&WinOptions {
            no_online_account: true,
            no_bitlocker: true,
            ..Default::default()
        });
        assert!(xml.contains("<settings pass=\"oobeSystem\">"));
        assert!(xml.contains("<HideOnlineAccountScreens>true</HideOnlineAccountScreens>"));
        assert!(xml.contains("PreventDeviceEncryption"));
        assert!(xml.contains("BypassNRO"));
        assert!(!xml.contains("LabConfig"));
    }

    #[test]
    fn registry_paths_are_xml_escaped() {
        let xml = generate(&WinOptions {
            no_bitlocker: true,
            ..Default::default()
        });
        // No raw quotes inside CommandLine attributes.
        assert!(xml.contains("CommandLine>reg add"), "{xml}");
        assert!(!xml.contains("CommandLine=\"reg"), "{xml}");
    }
}
